import { RiPlaneFill } from 'react-icons/ri'

import { routePath, menuItems } from 'utils/enums'

const {
  toDashboard,
  toWidgets,
  toUIElements,
  toAdvanceUI,
  toFormElements,
  toEditors,
  toCharts,
  toTables,
  toPopups,
  toNotification,
  toIcons,
  toMaps,
  toUserPages,
  toErrorPages,
  toGeneralPages,
  toECommerce,
  toEMail,
  toCalendar,
  toTodoList,
  toGallery,
  toDocumentation,
} = routePath
const {
  dashboard,
  widgets,
  UIElements,
  advanceUI,
  formElements,
  editors,
  charts,
  tables,
  popups,
  notification,
  icons,
  maps,
  userPages,
  errorPages,
  generalPages,
  ECommerce,
  Email,
  calendar,
  todoList,
  gallery,
  documentation,
} = menuItems

export const sidebarMenuItems = [
  {
    key: 1,
    icon: <RiPlaneFill />,
    path: toDashboard,
    name: dashboard,
    routesArray: [toDashboard],
    selected: true,
    subMenu: [],
  },
  {
    key: 2,
    icon: <RiPlaneFill />,
    path: toWidgets,
    name: widgets,
    routesArray: [toWidgets],
    selected: true,
    subMenu: [],
  },
  {
    key: 3,
    icon: <RiPlaneFill />,
    path: toUIElements,
    name: UIElements,
    routesArray: [toUIElements],
    selected: true,
    subMenu: [],
  },
  {
    key: 4,
    icon: <RiPlaneFill />,
    path: toAdvanceUI,
    name: advanceUI,
    routesArray: [toAdvanceUI],
    selected: true,
    subMenu: [],
  },
  {
    key: 5,
    icon: <RiPlaneFill />,
    path: toFormElements,
    name: formElements,
    routesArray: [toFormElements],
    selected: true,
    subMenu: [],
  },
  {
    key: 5,
    icon: <RiPlaneFill />,
    path: toFormElements,
    name: formElements,
    routesArray: [toFormElements],
    selected: true,
    subMenu: [],
  },
  {
    key: 6,
    icon: <RiPlaneFill />,
    path: toEditors,
    name: editors,
    routesArray: [toEditors],
    selected: true,
    subMenu: [],
  },
  {
    key: 7,
    icon: <RiPlaneFill />,
    path: toCharts,
    name: charts,
    routesArray: [toCharts],
    selected: true,
    subMenu: [],
  },
  {
    key: 8,
    icon: <RiPlaneFill />,
    path: toTables,
    name: tables,
    routesArray: [toTables],
    selected: true,
    subMenu: [],
  },
  {
    key: 9,
    icon: <RiPlaneFill />,
    path: toPopups,
    name: popups,
    routesArray: [toPopups],
    selected: true,
    subMenu: [],
  },
  {
    key: 10,
    icon: <RiPlaneFill />,
    path: toNotification,
    name: notification,
    routesArray: [toNotification],
    selected: true,
    subMenu: [],
  },
  {
    key: 11,
    icon: <RiPlaneFill />,
    path: toIcons,
    name: icons,
    routesArray: [toIcons],
    selected: true,
    subMenu: [],
  },
  {
    key: 12,
    icon: <RiPlaneFill />,
    path: toMaps,
    name: maps,
    routesArray: [toMaps],
    selected: true,
    subMenu: [],
  },
  {
    key: 13,
    icon: <RiPlaneFill />,
    path: toUserPages,
    name: userPages,
    routesArray: [toUserPages],
    selected: true,
    subMenu: [],
  },
  {
    key: 14,
    icon: <RiPlaneFill />,
    path: toErrorPages,
    name: errorPages,
    routesArray: [toErrorPages],
    selected: true,
    subMenu: [],
  },
  {
    key: 15,
    icon: <RiPlaneFill />,
    path: toGeneralPages,
    name: generalPages,
    routesArray: [toGeneralPages],
    selected: true,
    subMenu: [],
  },
  {
    key: 16,
    icon: <RiPlaneFill />,
    path: toECommerce,
    name: ECommerce,
    routesArray: [toECommerce],
    selected: true,
    subMenu: [],
  },
  {
    key: 17,
    icon: <RiPlaneFill />,
    path: toEMail,
    name: Email,
    routesArray: [toEMail],
    selected: true,
    subMenu: [],
  },
  {
    key: 18,
    icon: <RiPlaneFill />,
    path: toCalendar,
    name: calendar,
    routesArray: [toCalendar],
    selected: true,
    subMenu: [],
  },
  {
    key: 19,
    icon: <RiPlaneFill />,
    path: toTodoList,
    name: todoList,
    routesArray: [toTodoList],
    selected: true,
    subMenu: [],
  },
  {
    key: 20,
    icon: <RiPlaneFill />,
    path: toGallery,
    name: gallery,
    routesArray: [toGallery],
    selected: true,
    subMenu: [],
  },
  {
    key: 21,
    icon: <RiPlaneFill />,
    path: toDocumentation,
    name: documentation,
    routesArray: [toDocumentation],
    selected: true,
    subMenu: [],
  },
]
