export const routePath = {
  toDashboard: '/',
  toWidgets: '/widgets',
  toUIElements: '/UI-elements',
  toAdvanceUI: '/advance-UI',
  toFormElements: '/form-elements',
  toEditors: '/editors',
  toCharts: '/charts',
  toTables: '/tables',
  toPopups: '/popups',
  toNotification: '/notification',
  toIcons: '/icons',
  toMaps: '/maps',
  toUserPages: '/user-pages',
  toErrorPages: '/error-pages',
  toGeneralPages: '/general-pages',
  toECommerce: '/e-commerce',
  toEMail: '/e-mail',
  toCalendar: '/calendar',
  toTodoList: '/todo-list',
  toGallery: '/gallery',
  toDocumentation: '/documentation',
}

export enum menuItems {
  dashboard = 'Dashboard',
  widgets = 'Widgets',
  UIElements = 'UI Elements',
  advanceUI = 'Advanced UI',
  formElements = 'Form Elements',
  editors = 'Editors',
  charts = 'Charts',
  tables = 'Tables',
  popups = 'Popups',
  notification = 'Notifications',
  icons = 'Icons',
  maps = 'Maps',
  userPages = 'User Pages',
  errorPages = 'Error Pages',
  generalPages = 'General Pages',
  ECommerce = 'E-Commerce',
  Email = 'E-mail',
  calendar = 'Calendar',
  todoList = 'Todo List',
  gallery = 'Gallery',
  documentation = 'Documentation',
}

export enum status {
  inProcess = 'Process',
  open = 'Open',
  onHold = 'On Hold',
}
